version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # Specify your desired Node.js version
    commands:
      - echo "Installing dependencies"
      - sudo npm install
  build:
    commands:
      - echo "Building the project"
      - sudo npm run build
  post_build:
    commands:
      - echo "Copying build files to target directory"
      - sudo cp -r ./build/* /var/www/html/frontend
      - echo "Restarting Nginx service"
      - sudo systemctl restart nginx

artifacts:
  files:
    - '**/*'

