version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20 # Specify your desired Node.js version
    commands:
      - echo "Navigating to the frontend directory"
      - cd frontend
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Building the project"
      - npm run build
  post_build:
    commands:
      - echo "Fetching PEM key from Secrets Manager"
      - aws secretsmanager get-secret-value --secret-id devopsfrom --query SecretString --output text > /tmp/key.pem
      - chmod 600 /tmp/key.pem
      - echo "Copying build files to the EC2 instance"
      - scp -i /tmp/key.pem -r ./frontend/build/* ubuntu@3.89.119.255:/var/www/html/frontend/build/
      - echo "Restarting Nginx service on the EC2 instance"
      - ssh -i /tmp/key.pem ubuntu@3.89.119.255 "sudo systemctl restart nginx"
      - echo "Cleaning up temporary key file"
      - rm -f /tmp/key.pem

artifacts:
  files:
    - '**/*'
